import { User, Task, Workflow, Team, Channel, Notification, CalendarEvent } from "./types"

// Mock Users
export const mockUsers: User[] = [
  {
    id: "1",
    name: "John Doe",
    email: "john@flowdesk.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
    role: "admin",
    status: "active",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane@flowdesk.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    role: "manager",
    status: "active",
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "3",
    name: "Mike Johnson",
    email: "mike@flowdesk.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike",
    role: "member",
    status: "active",
    createdAt: new Date("2024-03-05"),
  },
  {
    id: "4",
    name: "Sarah Wilson",
    email: "sarah@flowdesk.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    role: "member",
    status: "active",
    createdAt: new Date("2024-03-20"),
  },
  {
    id: "5",
    name: "Tom Brown",
    email: "tom@flowdesk.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tom",
    role: "member",
    status: "inactive",
    createdAt: new Date("2024-04-01"),
  },
]

// Mock Tasks
export const mockTasks: Task[] = [
  {
    id: "t1",
    title: "Design homepage mockup",
    description: "Create high-fidelity mockups for the new homepage redesign",
    status: "completed",
    priority: "high",
    assignee: mockUsers[1],
    dueDate: new Date("2026-01-15"),
    tags: ["design", "ui"],
    workflowId: "w1",
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-14"),
  },
  {
    id: "t2",
    title: "Implement authentication API",
    description: "Build JWT-based authentication endpoints",
    status: "in-progress",
    priority: "urgent",
    assignee: mockUsers[2],
    dueDate: new Date("2026-01-20"),
    tags: ["backend", "api", "security"],
    workflowId: "w1",
    createdAt: new Date("2026-01-05"),
    updatedAt: new Date("2026-01-18"),
  },
  {
    id: "t3",
    title: "Write unit tests",
    description: "Add comprehensive test coverage for core modules",
    status: "todo",
    priority: "medium",
    assignee: mockUsers[3],
    dueDate: new Date("2026-01-25"),
    tags: ["testing", "qa"],
    workflowId: "w1",
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-01-10"),
  },
  {
    id: "t4",
    title: "Database optimization",
    description: "Optimize slow queries and add proper indexing",
    status: "review",
    priority: "high",
    assignee: mockUsers[2],
    dueDate: new Date("2026-01-22"),
    tags: ["backend", "database"],
    workflowId: "w2",
    createdAt: new Date("2026-01-08"),
    updatedAt: new Date("2026-01-17"),
  },
  {
    id: "t5",
    title: "Mobile responsive fixes",
    description: "Fix layout issues on mobile devices",
    status: "todo",
    priority: "low",
    assignee: mockUsers[1],
    dueDate: new Date("2026-01-30"),
    tags: ["frontend", "mobile"],
    workflowId: "w1",
    createdAt: new Date("2026-01-12"),
    updatedAt: new Date("2026-01-12"),
  },
  {
    id: "t6",
    title: "User feedback integration",
    description: "Implement user feedback widget and analytics",
    status: "in-progress",
    priority: "medium",
    assignee: mockUsers[3],
    dueDate: new Date("2026-01-28"),
    tags: ["frontend", "analytics"],
    createdAt: new Date("2026-01-14"),
    updatedAt: new Date("2026-01-18"),
  },
]

// Mock Workflows
export const mockWorkflows: Workflow[] = [
  {
    id: "w1",
    name: "Product Development",
    description: "Standard workflow for product feature development",
    stages: [
      { id: "s1", name: "Backlog", order: 0, color: "#6b7280" },
      { id: "s2", name: "In Progress", order: 1, color: "#3b82f6" },
      { id: "s3", name: "Review", order: 2, color: "#f59e0b" },
      { id: "s4", name: "Done", order: 3, color: "#22c55e" },
    ],
    createdBy: mockUsers[0],
    teamId: "team1",
    status: "active",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "w2",
    name: "Bug Tracking",
    description: "Workflow for tracking and resolving bugs",
    stages: [
      { id: "s5", name: "Reported", order: 0, color: "#ef4444" },
      { id: "s6", name: "Investigating", order: 1, color: "#f59e0b" },
      { id: "s7", name: "Fixing", order: 2, color: "#3b82f6" },
      { id: "s8", name: "Testing", order: 3, color: "#8b5cf6" },
      { id: "s9", name: "Resolved", order: 4, color: "#22c55e" },
    ],
    createdBy: mockUsers[1],
    teamId: "team1",
    status: "active",
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "w3",
    name: "Marketing Campaign",
    description: "Workflow for marketing campaign management",
    stages: [
      { id: "s10", name: "Planning", order: 0, color: "#6b7280" },
      { id: "s11", name: "Content Creation", order: 1, color: "#ec4899" },
      { id: "s12", name: "Approval", order: 2, color: "#f59e0b" },
      { id: "s13", name: "Scheduled", order: 3, color: "#3b82f6" },
      { id: "s14", name: "Published", order: 4, color: "#22c55e" },
    ],
    createdBy: mockUsers[0],
    teamId: "team2",
    status: "active",
    createdAt: new Date("2024-03-01"),
  },
]

// Mock Teams
export const mockTeams: Team[] = [
  {
    id: "team1",
    name: "Engineering",
    description: "Product development and engineering team",
    members: [
      { user: mockUsers[0], role: "owner", joinedAt: new Date("2024-01-01") },
      { user: mockUsers[2], role: "admin", joinedAt: new Date("2024-01-15") },
      { user: mockUsers[3], role: "member", joinedAt: new Date("2024-02-01") },
    ],
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "team2",
    name: "Design",
    description: "UI/UX and product design team",
    members: [
      { user: mockUsers[1], role: "owner", joinedAt: new Date("2024-01-10") },
      { user: mockUsers[3], role: "member", joinedAt: new Date("2024-02-15") },
    ],
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "team3",
    name: "Marketing",
    description: "Marketing and growth team",
    members: [
      { user: mockUsers[0], role: "admin", joinedAt: new Date("2024-03-01") },
      { user: mockUsers[4], role: "member", joinedAt: new Date("2024-03-15") },
    ],
    createdAt: new Date("2024-03-01"),
  },
]

// Mock Channels
export const mockChannels: Channel[] = [
  {
    id: "ch1",
    name: "general",
    type: "team",
    members: mockUsers,
    lastMessage: {
      id: "m1",
      content: "Hey team, the new sprint starts tomorrow!",
      sender: mockUsers[0],
      channelId: "ch1",
      createdAt: new Date("2026-01-18T10:30:00"),
      readBy: ["1", "2"],
    },
    unreadCount: 3,
  },
  {
    id: "ch2",
    name: "engineering",
    type: "group",
    members: [mockUsers[0], mockUsers[2], mockUsers[3]],
    lastMessage: {
      id: "m2",
      content: "PR is ready for review",
      sender: mockUsers[2],
      channelId: "ch2",
      createdAt: new Date("2026-01-18T09:15:00"),
      readBy: ["1", "3"],
    },
    unreadCount: 1,
  },
  {
    id: "ch3",
    name: "Jane Smith",
    type: "direct",
    members: [mockUsers[0], mockUsers[1]],
    lastMessage: {
      id: "m3",
      content: "Can we discuss the design feedback?",
      sender: mockUsers[1],
      channelId: "ch3",
      createdAt: new Date("2026-01-18T08:45:00"),
      readBy: ["2"],
    },
    unreadCount: 1,
  },
]

// Mock Messages
export const mockMessages = [
  {
    id: "msg1",
    channelId: "ch1",
    sender: mockUsers[0],
    content: "Hey team, the new sprint starts tomorrow!",
    timestamp: new Date("2026-01-18T10:30:00").toISOString(),
    reactions: [{ emoji: "👍", count: 3 }],
  },
  {
    id: "msg2",
    channelId: "ch1",
    sender: mockUsers[2],
    content: "Sounds great! I've finished the API work.",
    timestamp: new Date("2026-01-18T10:32:00").toISOString(),
    reactions: [],
  },
  {
    id: "msg3",
    channelId: "ch1",
    sender: mockUsers[1],
    content: "I'll have the designs ready by EOD.",
    timestamp: new Date("2026-01-18T10:35:00").toISOString(),
    reactions: [{ emoji: "🎉", count: 2 }],
  },
  {
    id: "msg4",
    channelId: "ch2",
    sender: mockUsers[2],
    content: "PR is ready for review",
    timestamp: new Date("2026-01-18T09:15:00").toISOString(),
    reactions: [],
  },
  {
    id: "msg5",
    channelId: "ch2",
    sender: mockUsers[0],
    content: "I'll take a look at it now.",
    timestamp: new Date("2026-01-18T09:20:00").toISOString(),
    reactions: [],
  },
  {
    id: "msg6",
    channelId: "ch3",
    sender: mockUsers[1],
    content: "Can we discuss the design feedback?",
    timestamp: new Date("2026-01-18T08:45:00").toISOString(),
    reactions: [],
  },
  {
    id: "msg7",
    channelId: "ch3",
    sender: mockUsers[0],
    content: "Sure! What aspects would you like to go over?",
    timestamp: new Date("2026-01-18T08:50:00").toISOString(),
    reactions: [],
  },
]

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: "n1",
    title: "Task Assigned",
    message: "You have been assigned to 'Design homepage mockup'",
    type: "info",
    read: false,
    actionUrl: "/tasks/t1",
    createdAt: new Date("2026-01-18T11:00:00"),
  },
  {
    id: "n2",
    title: "Task Completed",
    message: "Mike completed 'Implement authentication API'",
    type: "success",
    read: false,
    actionUrl: "/tasks/t2",
    createdAt: new Date("2026-01-18T10:30:00"),
  },
  {
    id: "n3",
    title: "Deadline Approaching",
    message: "Task 'Write unit tests' is due in 2 days",
    type: "warning",
    read: true,
    actionUrl: "/tasks/t3",
    createdAt: new Date("2026-01-17T15:00:00"),
  },
  {
    id: "n4",
    title: "New Team Member",
    message: "Sarah Wilson joined the Engineering team",
    type: "info",
    read: true,
    actionUrl: "/team",
    createdAt: new Date("2026-01-16T09:00:00"),
  },
  {
    id: "n5",
    title: "Build Failed",
    message: "CI/CD pipeline failed for branch 'feature/auth'",
    type: "error",
    read: false,
    actionUrl: "/tasks/t2",
    createdAt: new Date("2026-01-18T08:00:00"),
  },
]

// Mock Calendar Events
export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: "e1",
    title: "Sprint Planning",
    description: "Plan tasks for the upcoming sprint",
    start: new Date("2026-01-20T10:00:00"),
    end: new Date("2026-01-20T12:00:00"),
    type: "meeting",
  },
  {
    id: "e2",
    title: "Design Review",
    description: "Review homepage mockups",
    start: new Date("2026-01-19T14:00:00"),
    end: new Date("2026-01-19T15:00:00"),
    type: "meeting",
    taskId: "t1",
  },
  {
    id: "e3",
    title: "Auth API Deadline",
    start: new Date("2026-01-20T17:00:00"),
    end: new Date("2026-01-20T17:00:00"),
    type: "deadline",
    taskId: "t2",
  },
  {
    id: "e4",
    title: "Team Standup",
    description: "Daily team sync",
    start: new Date("2026-01-18T09:00:00"),
    end: new Date("2026-01-18T09:30:00"),
    type: "meeting",
  },
  {
    id: "e5",
    title: "Code Freeze Reminder",
    start: new Date("2026-01-25T09:00:00"),
    end: new Date("2026-01-25T09:00:00"),
    type: "reminder",
  },
]

// Analytics Data
export const mockAnalytics = {
  tasksCompleted: 24,
  tasksInProgress: 8,
  tasksTodo: 12,
  tasksReview: 4,
  productivityScore: 87,
  averageCompletionTime: 3.2,
  weeklyData: [
    { day: "Mon", completed: 4, created: 6 },
    { day: "Tue", completed: 6, created: 3 },
    { day: "Wed", completed: 3, created: 5 },
    { day: "Thu", completed: 7, created: 4 },
    { day: "Fri", completed: 5, created: 2 },
    { day: "Sat", completed: 1, created: 0 },
    { day: "Sun", completed: 0, created: 1 },
  ],
  monthlyData: [
    { month: "Aug", completed: 45, created: 52 },
    { month: "Sep", completed: 58, created: 61 },
    { month: "Oct", completed: 62, created: 55 },
    { month: "Nov", completed: 71, created: 68 },
    { month: "Dec", completed: 54, created: 49 },
    { month: "Jan", completed: 24, created: 28 },
  ],
  teamPerformance: [
    { name: "John Doe", completed: 12, score: 92 },
    { name: "Jane Smith", completed: 8, score: 88 },
    { name: "Mike Johnson", completed: 15, score: 95 },
    { name: "Sarah Wilson", completed: 6, score: 78 },
  ],
  tasksByPriority: [
    { priority: "Urgent", count: 3 },
    { priority: "High", count: 8 },
    { priority: "Medium", count: 15 },
    { priority: "Low", count: 6 },
  ],
}

// Current logged-in user
export const currentUser = mockUsers[0]
